# -*- coding: utf-8 -*-
"""OmniVoice - Clone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ykJNOTcRzTrsvT-FN5fUTi9Ud55in8A5
"""

# Install the latest OmniVoice package
!pip install -q omnivoice

# Alternatively, install the bleeding-edge version directly from GitHub:
# !pip install -q git+https://github.com/k2-fsa/OmniVoice.git

import torch
import torchaudio
from IPython.display import Audio, display
from omnivoice import OmniVoice

# Initialize and load model to GPU
model = OmniVoice.from_pretrained(
    "k2-fsa/OmniVoice",
    device_map="cuda:0",
    dtype=torch.float16
)

voice_library = {

}

# Target text you want the cloned voice to speak
target_text = "Api ini tidak punya lidah api. Tapi dia bisa membakar tanah... sampai tiga meter ke bawah. Ribuan liter air disemprot... apinya tetap menyala. Kok bisa? Januari sampai Juli 2026: dua ratus ribu hektare terbakar. Lebih dua kali lipat dari 2019."
ref_text="Kalian tau nggak guys, kalau ada sebuah sungai di Jogjakarta, ini itu diberi nama karena pernah ada gajah raksasa yang hilang dan tenggelam di sungai ini"  # Transcript of ref.wav

# Generate cloned speech
audio = model.generate(
    text=target_text,
    ref_audio="/content/famale-slow-pace.m4a",  # Path to your reference audio (WAV, MP3, FLAC)
    ref_text=ref_text,
    num_step=32,          # Diffusion steps (use 16 for faster speed, 32 for higher quality)
    speed=1.0             # Playback speed (0.5x to 2.0x)
)

# Save and playback in Colab (OmniVoice outputs at 24kHz)
output_path = "cloned_output.wav"

# Target text you want the cloned voice to speak
target_text = "Api ini tidak punya lidah api. Tapi dia bisa membakar tanah... sampai tiga meter ke bawah. Ribuan liter air disemprot... apinya tetap menyala. Kok bisa? Januari sampai Juli 2026: dua ratus ribu hektare terbakar. Lebih dua kali lipat dari 2019."
ref_text = "Alam semesta umurnya sekitar 13,8 Miliar tahun. Sekarang kita tuh udah nemuin seenggaknya puluhan planet yang kondisinya mirip sama bumi dan mendukung adanya kehidupan"

# Generate cloned speech
audio = model.generate(
    text=target_text,
    ref_audio="/content/female-medium-pace-2.m4a",  # Path to your reference audio (WAV, MP3, FLAC)
    ref_text=ref_text,  # Transcript of ref.wav
    num_step=32,          # Diffusion steps (use 16 for faster speed, 32 for higher quality)
    speed=0.7             # Playback speed (0.5x to 2.0x)
)

# Save and playback in Colab (OmniVoice outputs at 24kHz)
output_path = "cloned_output.wav"

import numpy as np
from IPython.display import Audio, display

# audio is a list, so pick the first item
waveform = np.array(audio[0]).squeeze()

display(Audio(waveform, rate=24000))

import soundfile as sf
import numpy as np

waveform = np.array(audio[0]).squeeze()
sf.write("cloned_output.wav", waveform, 24000)

import numpy as np
import soundfile as sf
from IPython.display import Audio, display

# 1. Define your scenes
# Script segmented per scene
scenes = [
    {
        "id": "scene_1",
        "text": "Api ini tidak punya lidah api. Tapi dia bisa membakar tanah... sampai tiga meter ke bawah."
    },
    {
        "id": "scene_2",
        "text": "Ribuan liter air disemprot... apinya tetap menyala. Kok bisa?"
    },
    {
        "id": "scene_3",
        "text": "Agustus dua ribu dua puluh enam. Delapan ribu enam ratus titik api di Kalimantan. Dan tiga dari empat... ada di dalam konsesi."
    },
    {
        "id": "scene_4",
        "text": "Mungkin kamu mikir: 'Ah, kebakaran hutan, urusan mereka.' Salah. Asap ini nggak tahu batas."
    },
    {
        "id": "scene_5",
        "text": "Asap gambut mengendap di permukaan tanah. Kamu napas langsung. P-M dua koma lima, karbon monoksida, bahkan sianida."
    },
    {
        "id": "scene_6",
        "text": "Januari sampai Juli dua ribu dua puluh enam: dua ratus ribu hektare terbakar. Lebih dua kali lipat dari dua ribu sembilan belas."
    },
    {
        "id": "scene_7",
        "text": "Kesalahan pertama: mikir ini gara-gara El Niño. El Niño cuma pemicu. Bahan bakarnya... udah disiapin puluhan tahun."
    },
    {
        "id": "scene_8",
        "text": "Kesalahan kedua: mikir ini ulah petani. Faktanya: tujuh puluh empat persen titik api ada di dalam konsesi korporasi. Bukan ladang Dayak."
    },
    {
        "id": "scene_9",
        "text": "Dan kesalahan ketiga: mikir air bisa menyelesaikan ini. Gambut kering itu bukan kebakaran. Dia mengquina."
    },
    {
        "id": "scene_10",
        "text": "Kalau masih nonton sampai sini — kamu lebih paham dari sebagian besar pejabat. Komen 'BASAH' kalau kamu setuju."
    },
    {
        "id": "scene_11",
        "text": "Gini cara bacanya. Gambut itu spons. Spons yang nyimpan air ribuan tahun. Spons yang nyimpan karbon lebih banyak dari hutan mana pun."
    },
    {
        "id": "scene_12",
        "text": "Tahun seribu sembilan ratus sembilan puluh lima, proyek sejuta hektar menggali kanal ribuan kilometer. Air dialirkan keluar. Sponsnya jadi kering keset. Gagal. Ditinggal. Tapi kanalnya? Masih ada sampai sekarang."
    },
    {
        "id": "scene_13",
        "text": "Sekarang? Proyek pangan baru datang ke tanah yang sama. Eskavator tenggelam. Padi gagal. Kanal baru digali. Sejarah nggak cuma berulang — dia nge-loop."
    },
    {
        "id": "scene_14",
        "text": "Mau bukti? Kanal drainase bikin risiko kebakaran naik empat setengah kali lipat. Itu riset fisika gambut, bukan opini."
    },
    {
        "id": "scene_15",
        "text": "Hukum? Tujuh puluh dua orang ditangkap. Barang buktinya: tiga puluh lima korek api. Tapi korporasi yang diselidiki? Empat."
    },
    {
        "id": "scene_16",
        "text": "Tapi ada yang berhasil. Katingan Mentaya: gambut tetap basah, dan malah menghasilkan. Dari karbon."
    },
    {
        "id": "scene_17",
        "text": "Solusinya bukan roket: biarin gambut basah. Tanam sagu, jelutung, purun — tanaman yang butuh air, bukan yang takut air. Untungnya nyata, karbonnya nyata."
    },
    {
        "id": "scene_18",
        "text": "Bagikan video ini. Karena kalau semua orang mikir ini cuma musibah alam... kamu udah tahu: ini kebijakan. Dan kebijakan bisa diubah."
    }
]

# 2. Settings
SAMPLE_RATE = 24000
REF_AUDIO = "/content/famale-slow-pace.m4a"
REF_TEXT = "Kalian tau nggak guys, kalau ada sebuah sungai di Jogjakarta, ini itu diberi nama karena pernah ada gajah raksasa yang hilang dan tenggelam di sungai ini"  # Add transcript string if you have it, or keep None for auto-ASR
SILENCE_DURATION = 0.35  # Pause between scenes in seconds (0.35s is natural)

# Create a silence array to insert between scenes
silence_gap = np.zeros(int(SAMPLE_RATE * SILENCE_DURATION), dtype=np.float32)

audio_segments = []

# 3. Generate audio scene by scene
for i, scene in enumerate(scenes):
    print(f"Generating [{scene['id']}] ({i+1}/{len(scenes)})...")

    # Generate speech
    output = model.generate(
        text=scene["text"],
        ref_audio=REF_AUDIO,
        ref_text=REF_TEXT,
        num_step=32,
        speed=1.0
    )

    # Extract waveform numpy array
    segment = np.array(output[0], dtype=np.float32).squeeze()

    # (Optional) Save individual scene audio
    sf.write(f"{scene['id']}.wav", segment, SAMPLE_RATE)

    # Append to list with a trailing pause (except for the very last scene)
    audio_segments.append(segment)
    if i < len(scenes) - 1:
        audio_segments.append(silence_gap)

# 4. Concatenate all segments into one final audio track
final_waveform = np.concatenate(audio_segments)

# 5. Save and preview final merged audio
final_output_path = "final_full_voiceover.wav"
sf.write(final_output_path, final_waveform, SAMPLE_RATE)
print(f"\n Done! Saved final output to {final_output_path}")

display(Audio(final_waveform, rate=SAMPLE_RATE))

"""# Transcribe the Final Result"""

!pip install pipx

!pipx install whisperx

!pipx ensurepath

!source ~/.bashrc && whisperx '/content/final_full_voiceover.wav' --model base --language id --highlight_words True

